// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYBAXkevrhRh-5cuP8Y6gZvlYzzu-KK-s',
    appId: '1:1048735671855:web:1355e08768ce4b01a6c8da',
    messagingSenderId: '1048735671855',
    projectId: 'patienttracking-97a81',
    authDomain: 'patienttracking-97a81.firebaseapp.com',
    storageBucket: 'patienttracking-97a81.appspot.com',
    measurementId: 'G-BL0GNNRT55',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwX1yXhdUhALRndfjHlF9kC6Qa57DfwZw',
    appId: '1:1048735671855:android:726527cc2673cc8fa6c8da',
    messagingSenderId: '1048735671855',
    projectId: 'patienttracking-97a81',
    storageBucket: 'patienttracking-97a81.appspot.com',
  );
}
